### ISSUE TITLE
Suggestion: Generic timer / Reminders

### ISSUE THREAD

**Issue by corylulu** [d0lb33/TimerTracker#2]
Should make a generic timer input method as well like:

> /n Shen 180 ult
> /n Game 5 mid inhib respawn
> /n Ezreal 4:30 Flash (forgot to time)

Assuming any number below 20 is minutes and above 20 is seconds and if it has a colon, parse it as M:SS.

And would also be useful if there was a 30 second - 1 minute reminder option that can either be enabled by default or by a command like:

> /n Shen 180 ult -r30 

I would offer to implement it myself, but I refuse to dirty my hands with Visual Basic, I'd have to convert it to C# first xD

**Comment by d0lb33** [comment]
@corylulu i am looking into rewriting it, so hopefully to fix this issue. I am also going to include things like Shen ult, and TF ult, karthus ult, and any other ult >100 secs... I need to find a better way to detect what somewhat types, instead of the idea I have going here. This is really just my first release of the program. I expect to see a lot of things to be changes. Thanks for your insight, and I admire you and Moobeats work! :)
